### ISSUE TITLE
Issue with cloud version don't allow propper QnA edition

### ISSUE THREAD

**Issue by ElCuboNegro** [botpress/studio#396]
```
VM4 sandbox_bundle:93 Unable to load preload script: C:\Users\jalba\AppData\Local\Programs\botpress-studio\resources\app.asar\dist\main\preload.js
(anonymous) @ VM4 sandbox_bundle:93
VM4 sandbox_bundle:93 ReferenceError: module is not defined
    at <anonymous>:68:1
    at <anonymous>:69:12
    at runPreloadScript (VM4 sandbox_bundle:93:2213)
    at Object.<anonymous> (VM4 sandbox_bundle:93:2480)
    at ./lib/sandboxed_renderer/init.ts (VM4 sandbox_bundle:93:2636)
    at __webpack_require__ (VM4 sandbox_bundle:1:170)
    at VM4 sandbox_bundle:1:1242
    at ___electron_webpack_init__ (VM4 sandbox_bundle:1:1320)
    at VM4 sandbox_bundle:160:455
(anonymous) @ VM4 sandbox_bundle:93
react-dom.development.js:29840 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
2react-dom.development.js:86 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
printWarning @ react-dom.development.js:86
react-dom.development.js:86 Warning: componentWillMount has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: HotKeys, Redirect, Route, Router, Switch
printWarning @ react-dom.development.js:86
react-dom.development.js:86 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Route, Router, Switch
printWarning @ react-dom.development.js:86
react-dom.development.js:86 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: DiagramWidget
printWarning @ react-dom.development.js:86
react-dom.development.js:86 Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: DiagramWidget
printWarning @ react-dom.development.js:86
bluebird.js:1590 Unhandled rejection TypeError: expecting an array or an iterable object but got [object Null]
printWarning @ bluebird.js:1590
3react-dom.development.js:86 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
printWarning @ react-dom.development.js:86
:2001/bot/Spongy/messaging/message-to-event/888b32ca-4884-4eba-ae57-409790227e56:1          Failed to load resource: the server responded with a status of 404 (Not Found)
react-dom.development.js:86 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: JSONNestedNode, JSONTree
printWarning @ react-dom.development.js:86
6react-dom.development.js:86 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
printWarning @ react-dom.development.js:86
index.js:316 Uncaught TypeError: Cannot read properties of undefined (reading 'formatMessage')
    at Object.tr (index.js:316:8978)
    at index.js:331:340498
    at Array.map (<anonymous>)
    at ao (index.js:331:340435)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26560:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at performSyncWorkOnRoot (react-dom.development.js:26085:1)
    at flushSyncCallbacks (react-dom.development.js:12042:1)
react-dom.development.js:18687 The above error occurred in the <ao> component:

    at ao (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:532088:340153)
    at div
    at div
    at ResizeSensor (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:22633:47)
    at div
    at InnerPopper (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:464107:35)
    at Popper (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:464271:31)
    at Transition (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:475533:30)
    at CSSTransition (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:474975:35)
    at div
    at TransitionGroup (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:476080:30)
    at Portal (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:22404:47)
    at Overlay (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:20776:47)
    at span
    at Manager (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:464012:35)
    at Popover (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:21645:47)
    at Tooltip (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:24897:47)
    at div
    at TextAreaList (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:589183:17)
    at div
    at div
    at QnA (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:588930:35)
    at div
    at div
    at div
    at FocusTrap (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:405277:5)
    at HotKeys (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:405488:5)
    at Container (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:571513:59)
    at QnAList (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:589377:35)
    at withLanguage
    at Connect (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:464691:28)
    at Route (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:466583:5)
    at Switch (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:467032:5)
    at div
    at http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:42196:36590
    at div
    at div
    at http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:42196:36845
    at div
    at http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:42196:36590
    at div
    at div
    at http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:42196:36845
    at div
    at div
    at FocusTrap (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:405277:5)
    at HotKeys (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:405488:5)
    at Layout (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:570916:35)
    at Connect (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:464691:28)
    at Switch (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:467032:5)
    at Router (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:466737:5)
    at RoutesRouter (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:571473:15)
    at Connect (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:464691:28)
    at App (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:564957:28)
    at Connect (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:464691:28)
    at div
    at FocusTrap (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:405277:5)
    at HotKeys (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:405488:5)
    at Provider (http://localhost:4000/assets/studio/ui/public/js/web.84b3ded867c0bb64cedc.js?af6f4f55c3dd1b46e488:464524:26)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18687
react-dom.development.js:12056 Uncaught TypeError: Cannot read properties of undefined (reading 'formatMessage')
    at Object.tr (index.js:316:8978)
    at index.js:331:340498
    at Array.map (<anonymous>)
    at ao (index.js:331:340435)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26560:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at performSyncWorkOnRoot (react-dom.development.js:26085:1)
    at flushSyncCallbacks (react-dom.development.js:12042:1)
    at flushSyncCallbacksOnlyInLegacyMode (react-dom.development.js:12021:1)
    at scheduleUpdateOnFiber (react-dom.development.js:25541:1)
    at Object.enqueueSetState (react-dom.development.js:14067:1)
```

**Comment by ElCuboNegro** [comment]
The error occurs when a link is selected inside the QnA window
